CREATE TABLE IF NOt EXISTS products(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pName TEXT NOT NULL,
    pPrice INTEGER NOT NULL,
    pCount INTERGER DEFAULT 1,
    pType INTEGER NOT NULL,
    pCategory INTERGER NOT NULL
)