CREATE TABLE IF NOT EXISTS products(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pName TEXT NOT NULL,
    pPrice INTEGER NOT NULL,
    pCount INTEGER DEFAULT 1,
    pType INTEGER NOT NULL,
    pCategory INTEGER NOT NULL
)